# batch_maps.sub -- run map creation for each patch

universe		= vanilla
executable              = /data/ohep2/hades/batch_maps.sh
requirements		= (machine != "calx098.ast.cam.ac.uk")&&(machine != "calx087.ast.cam.ac.uk")
getenv			= true
arguments               = "$(Process)"
should_transfer_files   = IF_NEEDED
when_to_transfer_output = ON_EXIT
request_memory		= 3000
log                     = /dev/null
output			= batch_maps.out
error			= batch_maps.error
notification		= never
queue 300
