# batch_maps.sub -- run map creation for each patch

universe		= vanilla
executable              = /data/ohep2/hades/null_test.sh
requirements		= (machine != "calx098.ast.cam.ac.uk")&&(machine != "calx087.ast.cam.ac.uk")
priority 		= 17
getenv			= true
arguments               = "$(Process)"
should_transfer_files   = IF_NEEDED
when_to_transfer_output = ON_EXIT
request_memory		= 7000
log                     = /dev/null
output			= null_test.out
error			= null_test.error
notification		= never
queue 8000 #5300
